id: A7B2BBA61
title: 'The Swift Steed of Garuḍa, King of Birds: An Instruction for Travelling to
  Sukhāvatī: A Visualization and Recitation of Uṣnīṣa-Sitātapatrā'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:50:47.398066
  last_modified_at: 2022-03-01 05:50:47.398069
