id: A7B2BBA61
title: 'The Blazing Tower: A Daily Practice of Uṣṇīṣa-Sitātapatrā'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:50:47.390766
  last_modified_at: 2022-03-01 05:50:47.390770
