id: A7B2BBA61
title: The Noble Dhāraṇī of The Supreme Accomplishment of Sitātapatrā Born from the
  Tathāgata’s Uṣṇīṣa, the Great Invincible Dispeller
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:50:47.395849
  last_modified_at: 2022-03-01 05:50:47.395856
